### ISSUE TITLE
Download folder still doesn't show up

### ISSUE THREAD

**Issue by Rapter44** [leoding86/webextension-pixiv-toolkit#145]
I was really hoping the new recent update would fix the downloading but for me it still doesn't work.
I tried everything, flipping on and off the "Allow extension takes over downloads" I even made sure that my chrome had that setting on, no matter what my folder will not pop up to let me select where I want a gif to be in.

**Comment by leoding86** [comment]
If the extension complete a download, you should find out the downloaded item in `chrome://downloads/` if you're using Chrome.

**Comment by Rapter44** [comment]
> If the extension complete a download, you should find out the downloaded item in `chrome://downloads/` if you're using Chrome.

Yeah no, it doesn't show up in downloads, because I'm trying to download it where my folder pops up so I can place the gif wherever I want it to be, I have "Allow extension takes over downloads" on and "Ask where to save each file before downloading" is enabled too

**Comment by leoding86** [comment]
Try the latest version [here](https://github.com/leoding86/webextension-pixiv-toolkit/releases/tag/5.2.1). Install crx version if you install the extension from Chrome web store.

**Comment by Rapter44** [comment]
> Try the latest version [here](https://github.com/leoding86/webextension-pixiv-toolkit/releases/tag/5.2.1). Install crx version if you install the extension from Chrome web store.

What do I do when I install the crx? Right now it's only downloading into my download folder even though I had it set to allow the extention to take over downloads

**Comment by leoding86** [comment]
I've published the latest version to Chrome Web Store. If you're using Chrome, the extension will be updated automatically shortly.

**Comment by Rapter44** [comment]
> I've published the latest version to Chrome Web Store. If you're using Chrome, the extension will be updated automatically shortly.

I uninstalled and installed the latest version and I'm still not getting the option to choose where to save a file, and yes I have "Ask where to save each file before downloading" enabled but there is a Red * sign so that could something but I don't know what

**Comment by leoding86** [comment]
You mean you want choose save folder when every each download is complete?

**Comment by Rapter44** [comment]
> You mean you want choose save folder when every each download is complete?

Yes, when a download is complete I want to choose where to save it instead of having it download in one folder just for me to move it to another
